### ISSUE TITLE
Regarding reverse solidus(\)

### ISSUE THREAD

**Issue by polsumeet3666** [shokuie/gsm7#1]
Hi @shokuie ,
we are implementing a project using smpp protocol for connecting to SMSC.
ideally in GSM 03.38  reverse solidus ("\") is converted to 0x1b2f

your lib is converted the same to 9b 17

is it expected behavior or i am not using lib properly ?

![image](https://user-images.githubusercontent.com/35520546/94129409-f2b99280-fe78-11ea-9190-dd173e9f235c.png)

**Comment by shokuie** [comment]
I'm not sure if you changed the library or not but decode does not take two arguments. Anyway, the backslash should be encoded to `0x9B17` as GSM7 is a septet based (7 bit) encoding. Here is how this happens:

```
0x1b (H) = 0001 1011 (B), 0x2f (H) = 0010 1111 (B)

A: 0001 1011 --> to 7 bit (drop bit #7) --> 001 1011 --> move bit# 0 of second octet to bit# 7 of the first octet --> 1001 1011  

B: 0010 1111 --> shift 1 bit to the right (already move bit# 7) --> 0001 0111 

C:  Output --> [A, B] = 1001 1011 (B), 0001 0111 (B) -> 0x9B (H), 0x17 (H)
```

**Comment by polsumeet3666** [comment]
hi @shokuie ,
Thanks for quick response.
I agree with above encoding logic completely.

I am using GSM7 encoding to send SMS messages using SMPP protocol.
as per docs, GSM-7 is the standard alphabet for SMS messages, written up in the standard [GSM 03.38](https://en.wikipedia.org/wiki/GSM_03.38). 
The GSM 7-bit default alphabet consists of 128 characters totally and each character is represented by 7 bits. 10 extra characters are defined in the GSM 7-bit default alphabet extension table and they have to be represented through an escape mechanism using the escape character (0x1B). The 10 extra characters are:

    Form feed

    Caret / circumflex

    Left curly bracket

    Right curly bracket

    Backslash

    Left square bracket

    Tilde

    Right square bracket

    Vertical bar

    Euro sign

The codes of the 10 characters above begin with 0x1B (i.e. the escape character), which indicates they are escaped sequences. For example, the code of the Backslash sign is 0x1B2F.

Hence I reported the issue.

**Comment by shokuie** [comment]
Closing this issue as everything looks correct and as expected. Feel free to reopen it if you find some issues.
